name: Testing case
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: "this key is a teting key"
        admin: admin
    steps:
      - uses: actions/checkout@v2
      - name: setup python 3.10.9
        uses: actions/checkout@v2
        with:
          python-version: 3.10.9
      - name: Installl
        run: |
          pip install -r requirements.txt
      - name: Lint8 with flake8
        run: |
          pip install -r requirements.txt
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install -r requirements.txt
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Test
        run: |
          pip install -r requirements.txt
          python manage.py test


